### ISSUE TITLE
bitset size is not extended properly

### ISSUE THREAD

**Issue by SNiLD** [mariokonrad/marnav#13]
`extend()` method checks the `capacity()` of vector instead of `size()`. I have fixed this in my branch with commit  https://github.com/mariokonrad/marnav/commit/8115b4b524da98854c857e3d9f728b8b7c563317 but this branch also has Visual Studio 2017 changes so I can create clean pull request.

This issue is revealed by running the `test-ais-sample` which asserts on access beyond the size of the data vector in bitset from `bitset(const_iterator first, const_iterator last)` -> `append()` -> `append_block()` -> `extend()`. This bitset constructor already increases the capacity of the data vector and adds the data itself but for the remainder bits uses `append()` for some reason. Maybe this whole path should be refactored to just use the append()?

**Comment by mariokonrad** [comment]
Thank you for the bug report. This is indeed a bug, and a subtle one.

I'd be happy to merge a specific PR, or I change it manually and push. Which one would you prefer? I'd prefer the former, so you appear in the history but it's more effort on your side, what do you think?

Regarding refactoring: yes, I'm considering this. I agree, this constructor is overburdened, but also the function `set_block` has the `else` path which is never taken (according to coverage).

**Comment by SNiLD** [comment]
It's better if you just change it manually and push. Less work that way.

**Comment by mariokonrad** [comment]
Very well. Is it ok for you if I mention you as 'https://github.com/SNiLD' in the commit message, or would you prefer something else?

**Comment by SNiLD** [comment]
That's fine.

**Comment by mariokonrad** [comment]
Or I commit the patch with `git commit --author="SNiLD"`. ?

**Comment by SNiLD** [comment]
That's fine as well. As long as the issue is fixed. ;)

**Comment by mariokonrad** [comment]
Ok. I just think, attribution is not unimportant and I don't want to be rude and publish someone else's effort as my own work.

**Comment by mariokonrad** [comment]
Pushed 35489f9ea241589327321b1c5ac85b5733e056f2
