### ISSUE TITLE
Errors during executable linking when using latest package

### ISSUE THREAD

**Issue by TriptoKnocker** [mariokonrad/marnav#16]
When building marnav from the latest released package (0.8.0), marnav will fail to link the various generated executables. I'm on Ubuntu 18.04, with GCC7.

The error received is:
``
c++: error: -E or -x required when input is from standard input
``

Having a poke through the CMakeLists file, I can easily spot the issue (at line 30 from the packaged version):
```cmake
### version handling
if(NOT ("${CMAKE_BUILD_TYPE}" MATCHES "Release"))
	set(PROJECT_VERSION "${PROJECT_VERSION}-${GIT_COMMIT_HASH_SHORT}")
endif()
message(STATUS "Project Vesion: ${PROJECT_VERSION}")
```

The git commit hash is missing as I'm using the packaged sources. Without ${GIT_COMMIT_HASH_SHORT} being set, the version gets set to '0.8.0-' which leads GCC to incorrectly think that I'm going to provide additional input from the terminal due to the trailing dash.

I now realise that this will only be a problem when using a non-release build type but as CMake defaults to not filling in  the build type, I'm sure that I'm not the only soul who would hit this rather minor issue.

Thanks for your time.

**Comment by mariokonrad** [comment]
Thank you for reporting, I'll look into the issue.

**Comment by mariokonrad** [comment]
Release v0.8.1 (d3baa26c4002b52150483889110a3c0ba3a76fc8) checks explicitly for the presence of a git repository. This resolves the bug.
