### ISSUE TITLE
Latitude, Longitude is almost always wrong.

### ISSUE THREAD

**Issue by mb12** [mariokonrad/marnav#2]
Here is a sample type 1 message, which is parsed incorrectly. 

!AIVDM,1,1,,A,15RTgt0PAso;90TKcjM8h6g208CQ,0*4A

The following website parses this message correctly.

http://www.maritec.co.za/tools/aisvdmvdodecoding/

Expected:

Longitude:123*23.7230'W	
Latitude: 48*22.8980'N	

However this library throws exception because it extracts longitude as 323.99704333333335

**Comment by mariokonrad** [comment]
Thanks, I'll look into it

**Comment by mb12** [comment]
@mariokonrad the issue is that longitude needs to be interpreted as 28 bit ints and latitude as 27 bit ints. For e.g. For longitude minutes Check that if the value is >= 0x8000000 then it needs to be interpreted as negative number.
I am running into correctness issues with other single line non AIS sentences as well. This library is discarding valid sentences.

**Comment by mariokonrad** [comment]
Yes, you are right. In the past I hadn't always the equipment available to test it properly, but I'm on it. This is clearly an error and affects other sentences with lat/lon as well. I probably will have a patch ready during this week.
Thanks again!

**Comment by mariokonrad** [comment]
The commit 0f96aa4 should resolve the issue. There was also a problem with the armoring, encoded payloads could contain invalid characters.
