### ISSUE TITLE
Missing `std::move` in `utils::optional`

### ISSUE THREAD

**Issue by solosuper** [mariokonrad/marnav#22]
Hi,
Fetching the value from a temporary [`utils::optional::value`](https://github.com/mariokonrad/marnav/blob/master/src/marnav/utils/optional.hpp#L106) raises a compiler error:

```c++
// message is a const std::unique_ptr<marnav::ais::message_01>&
double rot = message->get_rot().value();
```
```
(...)/optional.hpp:106:27: error: cannot bind rvalue reference of type ‘double&&’ to lvalue of type ‘double’
  T && value() && { return data_; }
```
---

Inserting a `std::move` solves the problem:
```c++
T && value() && { return std::move(data_); }
```

**Comment by solosuper** [comment]
By the way, do you have any plans on moving to C++17 and `std::optional`?

**Comment by mariokonrad** [comment]
Thanks for the info! May I ask which compiler/platform you are using?

Implementing the `utils::optional` is indeed a "temporary" solution, to support C++11 / GCC-4.9 which was at the time the standard compiler on the Raspi. Unfortunately time is short, but I have a couple of things in the backlog. Moving to C++17 is one of them. After the transition, I will replace `utils::optional` with `std::optional` and drop the support for older compilers. Unfortunately I am not able to name a time frame.

**Comment by solosuper** [comment]
Hi,
I am using Ubuntu 16.04 with GCC 7.3.0 from ppa:ubuntu-toolchain-r/test.

Do you consider switching to `std::optional` a big job? I guess I could submit a pull request, but unfortunately I do not have too much time myself.

Do you want a PR for this issue?

I want to say thank you for a great library.

**Comment by mariokonrad** [comment]
Unfortunately, the upgrade of the toolchain has quite some implications. It means to touch almost all files, `utils::optional` is used quite frequently. There is also the integration with CI, and other things C++14/17 can do (constexpr) I have postponed.
Before I drop older compilers, I'd like to do another numbered release. Just to have a specific version and marker for this transition.
Thank you for your offer, but I believe this is quite an undertaking and I'm not sure if I could merge a PR timely. I plan to do it in 2019.

Thanks again!

**Comment by mariokonrad** [comment]
Merged the PR. Closing the issue.
