### ISSUE TITLE
distance_ellipsoid_vincenty limitations

### ISSUE THREAD

**Issue by victorcoat** [mariokonrad/marnav#24]
This function (marnav/src/geo/geodesic line84) only returns azimuths from -pi/2 to pi/2 rad because of atan function used instead of atan2. 
It also returns a 0 distance for points on the same longitude (angles 0 and pi).

**Comment by mariokonrad** [comment]
You are right, thank you for pointing out.

**Comment by mariokonrad** [comment]
Fixed in commit 79b352bd49152c537ad1aa53a5ee122ab5418456.
