### ISSUE TITLE
Time should support `ms` too.

### ISSUE THREAD

**Issue by msis** [mariokonrad/marnav#25]
I have tested with a couple of systems and it seems that they do support ms (or at least decimals). 
Should we add it here [nmea::time](https://github.com/mariokonrad/marnav/blob/685c41870bdfea347fd3ed760992fb588376cbf3/src/marnav/nmea/time.cpp#L76) ?

See [gpsd](https://gpsd.gitlab.io/gpsd/NMEA.html) documentation as an example.

**Comment by mariokonrad** [comment]
Hi there!
Just for clarification, you are referring to the format `hhmmss.ss` as being shown in esr's documentation?

**Comment by mariokonrad** [comment]
A valid point. Thank you.
How about 41bf6c4fadc9c7e7c2d45501216a99c6af67abd8, rendering milliseconds if they matter, not if they are zero. This would be a compromise, rendering the time as being done on many devices, but rending with milliseconds if available.
What is you opinion?

**Comment by msis** [comment]
That would work perfectly.
Thanks for the quick implementation!

PS: Awesome library btw!

**Comment by mariokonrad** [comment]
Thanks!
