### ISSUE TITLE
error: C2678: binary '+=': no operator found which takes a left-hand operand of type 'const marnav::utils::bitset<uint8_t,void>::const_iterator' (or there is no acceptable conversion)

### ISSUE THREAD

**Issue by pavelpasha** [mariokonrad/marnav#26]
I am trying to copile this project with an Visual Studio 2017 compiler, but got an error on utils/bitset.hpp 148 line.

**Comment by mariokonrad** [comment]
Thanks for pointing this out. Unfortunately, MSVC is not officially supported.
