### ISSUE TITLE
RMB: fromWayPointId is before toWayPointId

### ISSUE THREAD

**Issue by karleisen** [mariokonrad/marnav#28]
According to the spec origin wayPointId is before destination wayPointId. But these are swapped in the implementation.
Here is the spec.

https://www.gpsinformation.org/dale/nmea.htm#RMB

Here is the implementation.

https://github.com/mariokonrad/marnav/blob/9ea23bbea36845aa331f2abf10720eeb20bdbbf9/include/marnav/nmea/rmb.hpp#L33

**Comment by mariokonrad** [comment]
Hi @karleisen 

Thanks for pointing out! You're right it is a bug, will fix it.

**Comment by mariokonrad** [comment]
Resolved by 5b5c404ffefd90cc7fcf102afadb51f4f9d9b4fd
