### ISSUE TITLE
RMB does not have a status indicator

### ISSUE THREAD

**Issue by karleisen** [mariokonrad/marnav#29]
RMB does not have a status indicator. The last field before checksum is arrival status. Here is the format of the RMB sentence in the spec.

https://www.gpsinformation.org/dale/nmea.htm#RMB

This is the field I am referring to.

https://github.com/mariokonrad/marnav/blob/9ea23bbea36845aa331f2abf10720eeb20bdbbf9/include/marnav/nmea/rmb.hpp#L89

**Comment by karleisen** [comment]
APB does not have a status indicator either.

https://www.gpsinformation.org/dale/nmea.htm#APB

**Comment by karleisen** [comment]
XTE does not have status indicator either.

https://www.gpsinformation.org/dale/nmea.htm#XTE

**Comment by karleisen** [comment]
RMC doesn't have it either. The last field before checksum is magnetic variation.

https://www.gpsinformation.org/dale/nmea.htm#RMC

http://aprs.gids.nl/nmea/#rmc

**Comment by mariokonrad** [comment]
APB: I remember to have read information on the net that there is in fact a mode indicator field after the heading/heading reference. Unfortunately I cannot find the reference right away.

XTE: does have a status indicator field, according to https://gpsd.gitlab.io/gpsd/NMEA.html#_xte_cross_track_error_measured, apparently NMEA 2.3 and newer

RMB: does have a mode indicator, information from here: https://gpsd.gitlab.io/gpsd/NMEA.html#_rmb_recommended_minimum_navigation_information

RMC: also has a mode indicator field, see here: https://gpsd.gitlab.io/gpsd/NMEA.html#_rmc_recommended_minimum_navigation_information, even the link you provided mentions it: https://www.gpsinformation.org/dale/nmea.htm#RMC, NMEA 2.3


RMB, RMC and XTE are implemented with this "NMEA 2.3 or later" in mind. As for APB, I need to search for the source of information that lead to the implementation, for now I'll leave it.

As a side note from the most linked site you provided, the author claims to have outdated and incorrect information (https://www.gpsinformation.org/dale/nmea.htm, Disclaimer). That's the same problem I have. I do not have the NMEA specification nor do I have access to it, nor did I ever see one. There is a lot of information on the internet, puzzling it together is the hard part.

Thanks for your effort. I appreciate the input.

**Comment by mariokonrad** [comment]
Apparently, this is going nowhere. Closing the issue.
