### ISSUE TITLE
ignore_checksum does not work for all nmea sentences.

### ISSUE THREAD

**Issue by mb12** [mariokonrad/marnav#3]
"$IIMWV,30,T,1.85,M,A"

```

std::unique_ptr<sentence> mwv::parse(
	const std::string & talker, const std::vector<std::string> & fields)
{
	if (fields.size() != 5) <== This will be 4 without checksum
		throw std::invalid_argument{"invalid number of fields in mwv::parse"};

```

**Comment by mariokonrad** [comment]
As far as I know, the string you mentioned is not a valid NMEA sentence, it lacks the `*xx` suffix, marking the end and the checksum. An exception will be thrown, if you try to parse with `nmea::make_sentence`.

**Comment by mb12** [comment]
It does not work even if one explicitly passes ignore_checksum=true in nmea::make_sentence.  checksum is optional in NMEA strings. Most  libraries automatically figure out if checksum is not appended and not check for it. This ensure that the library will work across a wide range of devices.

You can verify that the checksum is optional in NMEA at the link below.

http://www.kh-gps.de/nmea.faq

```
        The data is transmitted in the form of "sentences".  Each
        sentence starts with a "$", a two letter "talker ID", a three
        letter "sentence ID", followed by a number of data fields
        separated by commas, and terminated by an optional checksum, and
        a carriage return/line feed.  A sentence may contain up to 82
        characters including the "$" and CR/LF.
```

**Comment by mariokonrad** [comment]
As of now, `nmea::make_sentence` does not support optional checksums as described in the link you provided. Thank you for pointing that out.

However, the option `ignore_checksum` is not about optional checksums. It allows the user to intentionally ignore the checksum.

As stated in #4, at this point in time, optional checksums are not supported.

**Comment by mb12** [comment]
@mariokonrad 

I used the following to resolve this. It didn't require much changes in the codebase.

```
static std::string make_valid_nmea_string(const std::string& s) {
    auto const end_pos = s.find_first_of(sentence::end_token, 1);
    bool checksumabsent = (end_pos == std::string::npos) // end token not found
    ||
    (s.size() != end_pos + 3); // short or no checksum
    if(checksumabsent) {
        uint8_t sum = checksum(begin(s) + 1, begin(s) + s.size());
        char csum[80];
        sprintf(csum, "%02X", sum);
        std::string retval = s + "*" + std::string(csum);
        return retval;
    }
    else {
        return s;
    }
}

```
