### ISSUE TITLE
return type of sog is utils::optional<units::velocity> not utils::optional<units::knots> in the rmc sentence

### ISSUE THREAD

**Issue by JesvinJoseph** [mariokonrad/marnav#30]
Hi,
First of all, Thank you for the good Library 👍 

I have a small question. 

The return type of sog in the rmc sentence is utils::optional\<units::velocity\>. I think this by default converts the data into meter per second because of the to_base convertion in the basic dimention. But the data type of the sog variable is utils::optional\<units::knots\>.  How can I get the sog data in knots?
https://github.com/mariokonrad/marnav/blob/b9e83c7c5ee69c69d25304e4c142fab7e13503c5/include/marnav/nmea/rmc.hpp#L73
https://github.com/mariokonrad/marnav/blob/b9e83c7c5ee69c69d25304e4c142fab7e13503c5/include/marnav/nmea/rmc.hpp#L83

**Comment by mariokonrad** [comment]
Hello there!

Thanks!

I tried to keep the interfaces consistent, meaning member functions returning a velocity (quantity), to return `units::velocity`, not a specific unit. To get a unit from a compatible quantity (e.g. velocity -> knots), you just use the member function `get`, example:

```
auto v = rmc.get_sog(); // returns utils::optional<units::velocity>

// v is an optional,
// -> accesses its data assuming there is,
// get<...>() converts it into the desired unit
auto v_kn = v->get<units::knots>(); // v_kn is now units::knots

// for example also possible conversions from the same quantity:
auto v_mps = v->get<units::meters_per_second>(); 
auto v_kmh = v->get<units::kilometers_per_hour>();
```

This means, you get a velocity from rmc, then you decide which unit is useful for you.

If you need the numeric value (a `double` is the default type), just use `value()`, example:

```
auto v_kn = v->get<units::knots>();
std::cout << "SOG = " << v_kn.value() << '\n';

// or, of course, directly:
std::cout << "SOG = " << v->get<units::knots>().value() << '\n';
```

**Comment by JesvinJoseph** [comment]
Hi @mariokonrad , this really helps. Thank you very much 👍
