### ISSUE TITLE
marnav::utils::mmsi::sar_id() missing

### ISSUE THREAD

**Issue by std-any-emplace** [mariokonrad/marnav#33]
This is missing in class `mmsi`.
```
mmsi::value_type mmsi::sar_id() const
{
	if (!is_sar_aircraft())
		return initial_value;
	return value_ % 1000;
}
```

**Comment by mariokonrad** [comment]
Thanks for reporting! In fact, when I checked the MMSI implementation, there are other things missing, plus a bug. Will do an update soon.
