### ISSUE TITLE
Invalid SNR GSV value.

### ISSUE THREAD

**Issue by norton-dev** [mariokonrad/marnav#35]
Hi,

First of all thanks for providing nice library.

My GPS module feeds the lib with fallowing data:
`"$GPGSV,3,1,09,09,74,265,,04,63,066,14,06,50,261,,03,32,123,31*7B"`
As You can see SNR field is empty.

Because of uninitialized satellite_info (marnav/nmea/gsv.hpp) snr member has garbage value (252 in my case).

Please consider initialize satellite_info structure or change members type to optional.

Thanks.

**Comment by norton-dev** [comment]
https://www.st.com/content/ccc/resource/technical/document/user_manual/group1/26/c2/9b/50/db/3c/4f/e1/DM00495927/files/DM00495927.pdf/jcr:content/translations/en.DM00495927.pdf

- nice NMEA protocol description

**Comment by mariokonrad** [comment]
Resolves in d13a482112103e354c529432834cb76541976dd9
