### ISSUE TITLE
rte message formatting look wrong

### ISSUE THREAD

**Issue by ShadowTeolog** [mariokonrad/marnav#38]
void rte::append_data_to(std::string & s) const
{
	append(s, to_string(n_messages_));
	append(s, to_string(message_number_));
	append(s, to_string(message_mode_));

	if (n_messages_) {
		for (uint32_t i = 0; (i < n_messages_) && (i < max_waypoints); ++i) {
			append(s, waypoint_id_[i].value());
		}
	}
}
look like n_messages_ may not affect on waypoint output cout, if i not miss something.
Also look like format has differences, look like field RouteId missing:
//route send from navico maris ecdis sensor monitor(NMEA mode)
`"$IIRTE,1,1,c,2,001,002,003,004,005*0F"
"$IIWPL,4102.038,N,02900.753,E,001*6B"
"$IIWPL,4102.449,N,02901.939,E,002*69"
"$IIWPL,4103.268,N,02902.623,E,003*6B"
"$IIWPL,4103.268,N,02902.623,E,003*6B"
"$IIWPL,4103.268,N,02902.619,E,004*65"
"$IIWPL,4103.820,N,02902.875,E,005*66"
"$IIWPL,4103.820,N,02902.875,E,005*66"`

here after "C" exists additional filed for route id

**Comment by mariokonrad** [comment]
Hello there!

Thanks for the info. It appears that the implementation is based on an outdated version of https://gpsd.gitlab.io/gpsd/NMEA.html (respectively its former location). The document has been updated, this library not, yet.

**Comment by mariokonrad** [comment]
Issue addressed in 81d01c5f1dfc5ccd992d0a4b2ae7d5175c5213b8.

**Comment by mariokonrad** [comment]
Feedback has dried up. Closing the issue.
