### ISSUE TITLE
SignalK and sensors support on raspberry Pi ideas

### ISSUE THREAD

**Issue by mgrouch** [mariokonrad/marnav#41]
There are few other related C++ projects.

https://github.com/raffmont/signalk-server-cpp

https://github.com/epsilonrt/piduino

https://github.com/SignalK/SensESP

Just as an idea.
I think using those (at least first two) it would be possible to create marine multiplexer server for pi which would support many types of sensors (in similar fashion to SenseEsp)
but connected directly to Pi instead of ESP32.

Unfortunately https://github.com/raffmont/signalk-server-cpp
is not actively maintained but it could be a core of such server (it is based on marnav)

Thanks

**Comment by mariokonrad** [comment]
Nice idea. Good luck!
