### ISSUE TITLE
Checksum calculation without white space character

### ISSUE THREAD

**Issue by vcomert** [mariokonrad/marnav#42]
Hi,
I want to use the library with a standardized AIS equipment. When I use nmeatool to read data, checksum of some ALR packets is labeled with error as in the below
![nmeaTool](https://user-images.githubusercontent.com/4140647/175483017-958969d5-d18b-4bad-85b4-9f40dea80295.png)

However, when i checked the raw serial data , it comes with white spaces in the sentence after (AIS:).
![CuteComAis](https://user-images.githubusercontent.com/4140647/175483777-ae373282-5a5f-47cb-9fa3-cd0b410179fc.png)

 I figured out that the device calculates it with white spaces. What does the standard says about this character issue?

**Comment by mariokonrad** [comment]
Thanks for the insight. I do not know what the standard says, I do not have it, nor have I seen it.
Found the information about ALR here: https://www.cruisersforum.com/forums/f134/opencpn-and-external-nmea0183-alarms-81396.html
According to the examples provided there, it seems the alarm description can contain whitespaces.

Interpreting your screenshots, the device delivers

> `$AIALR,00000.00,026,A,V,AIS: no position sensor in use*5D`

but nmeatool prints

> `$AIALR,00000.00,026,A,V,AIS:nopositionsensorinuse*5D`

and claims the checksum is wrong? Yes, this clearly seems wrong.
Thanks for finding the bug!

**Comment by mariokonrad** [comment]
You're sure you're screenshots are accurate?

I try to reproduce and do:

```
echo "\$AIALR,00000.00,026,A,V,AIS: no position sensor in use*5D" | ./nmeatool
```

I get

```
$AIALR,00000.00,026,A,V,AIS: no position sensor in use*5D
        error: checksum error: checksum error (actual:6D, expected:5D)
```

There seems to be an issue with checksum, but I do not get your result.

**Comment by vcomert** [comment]
I 'm sure. You missed the one zero in the sentence after AIALR. There are six zero chars. The array that is seen in the picture is 
AIALR,000000.00,026,A,V,AIS: no position sensor in use    

Also, I fixed the bug in mu local code by getting char in 
https://github.com/mariokonrad/marnav/blob/34e0bd22f25e4f854567143a288ac2e6d9454ee8/src/marnav-io/nmea_reader.cpp#L68

by raw_ <= 31.

**Comment by mariokonrad** [comment]
You're right, I missed a `0`. Then I try again:
```
echo "\$AIALR,000000.00,026,A,V,AIS: no position sensor in use*5D" | ./nmeatool
```
yields the output:
```
$AIALR,000000.00,026,A,V,AIS: no position sensor in use*5D
        Name  : Set Alarm State
        Talker: Mobile AIS station
        Time UTC                       : 00:00:00
        Alarm Number                   : 26
        Alarm Condition                : Threshold Exceeded
        Alarm Acknowledge              : Not Acknowledged
        Alarm Text                     : AIS: no position sensor in use
```
Still does not match the output you presented with allegedly wrong checksum and spaces removed in the output of nmeatool.

As for the nmea_reader.cpp, this really looks like ignoring spaces and does not work for ALR. Will fix this, thanks!

**Comment by mariokonrad** [comment]
See b91e74c08b92f14eb3ad554084f9f5f694ccb01e, nmea_reader.cpp processes now spaces as well.

**Comment by vcomert** [comment]
I did not try to use with nmeatool with string input. Rather I used it with reading serial data. There may be a difference with input style. Anyway issue is closed. Thank you.
