### ISSUE TITLE
Problem with negative latitude or longitude to generate AIS message 1

### ISSUE THREAD

**Issue by rdouguet** [mariokonrad/marnav#51]
Hello,

I use this marnav library to parse and to create nmea sentence. on my project.

Today, I observed a problem to generate an AIS message 1 sentence.
I have no problem to generate AIS sentence if the latitude and longitude are positive (respectively North and East) but if I try to set a West longitude, the sentence are create without longitude value... It is similar to generate a South latitude.

I check different version to set negative value but none works :

```
ais::message_01 pos_report;

pos_report.set_lon(geo::longitude{3.3118});  // work correctly
pos_report.set_lon(geo::longitude{-3.3118}); // ko
pos_report.set_lon(geo::longitude{3.3118, geo::longitude::hemisphere::west});  // ko
pos_report.set_lon(geo::longitude{-3.3118, geo::longitude::hemisphere::west}); // ko
pos_report.set_lon(geo::longitude{3,31,18, geo::longitude::hemisphere::west});  // ko
```

If someone has a solution, I'm interested :)

Thanks,
Ronan.

**Comment by mariokonrad** [comment]
Hello Ronan,

just to make sure recreate the steps. You create a `message_01` with:
```
ais::message_01 pos_report;
pos_report.set_lon(geo::longitude{-3.3118});
// ... other fields
```
Then you encode the message using `auto v = ais::encode_message(pos_report)`, but the value (-3.3118 in this case) is somehow not there?

Would you mind to clarify with what you mean with: "if I try to set a West longitude, the sentence are create without longitude value"?

I did a quick round trip test for longitude with one of the cases you had problems with (create message_01, encode message, parse message check content), which succeeds:
```
TEST_F(Test_ais_message_01, github_issue_51_roundtrip_negative_east)
{
	const auto deg = -3.3118; // negative means western hemisphere

	ais::message_01 m;
	m.set_lon(geo::longitude{deg});

	const auto v = ais::encode_message(m);

	auto result = ais::make_message(v);
	ASSERT_TRUE(result != nullptr);

	auto m1 = ais::message_cast<ais::message_01>(result);
	ASSERT_TRUE(m1 != nullptr);

	const auto lon = m1->get_lon();
	ASSERT_TRUE(lon);
	EXPECT_EQ(geo::longitude::hemisphere::west, lon->hem());
	EXPECT_NEAR(deg, lon->get(), 1e-5);
}
```

**Comment by rdouguet** [comment]
Hello Mario,

Thanks for your feedback. I tried to create NMEA AIS frame by using example of "create_nmea_for_ais.cpp"

Here my code

```
double lat = 3.3118;
double lon = 47.43;
std::string s;
ais::message_01 pos_report;  

pos_report.set_sog(marnav::units::knots{8.2});
pos_report.set_cog(120.6);
pos_report.set_mmsi(utils::mmsi{2900056000});
pos_report.set_lon(geo::longitude{lon, geo::longitude::hemisphere::west});  
pos_report.set_lat(geo::latitude{lat});

// create payload
auto payload = ais::encode_message(pos_report);

// create NMEA sentences
for (uint32_t fragment = 0; fragment < payload.size(); ++fragment) 
{
  nmea::vdm vdm;
  vdm.set_n_fragments(payload.size());
  vdm.set_fragment(fragment + 1);
  vdm.set_radio_channel(nmea::ais_channel::B);
  vdm.set_payload(payload[fragment]);

  // collect, send or do something with the sentence...
  s = nmea::to_string(vdm);
  std::cout << s << "\n";
} 
```

I check the nmea sentence "s" on an ais online decoder and the sentence are correctly if the field latitute and longitude are positive. But when I set the latitude to negative value the field stay empty... I observed the same behavior when I send directly this nmea frame to openCPN.

Maybe my error comes when I create the NMEA sentences and not when the ais message is encoded.

Ronan.

**Comment by rdouguet** [comment]
Hello Mario,

Thanks for your help.

In fact, I tested exactly the same example that you did and I have not the same results

Longitude Positive = + 123...
`!AIVDM,1,1,,A,15RTgt0PAs`lnwJKcjLph6f408CQ,0*52`

Longitude Negative = - 123...
`!AIVDM,1,1,,A,15RTgt0PAsP0000KcjLph6f408CQ,0*5D`

In the first example, the latitude and longitude are corrects but the timestamp is not set to 33. And on the second packet, the longitude is not correct.

I downloaded this library there are a few months and maybe the error of longitude can be caused by the timestamp bit position which has been solved now?

I will try to update the library tomorrow to check if it fix this bug.

Thanks,
Ronan.

**Comment by mariokonrad** [comment]
I don't think there have been any changes in `geo::` or `ais::` in recent moths, but please try and don't hesitate with feedback!
In the meantime, I'll have a look at the sentences you provided.

Would you mind to provide the commit hash your version is on? Also, is it the entire code you tired posted in some comments earlier? If not, would you mind sharing the code (link or otherwise) that causes trouble?

Thanks Ronan.

**Comment by rdouguet** [comment]
Hi Mario,

Here the code with the same example that you did. I just insert this function in a ros package.
[marnav_test.zip](https://github.com/mariokonrad/marnav/files/10410845/marnav_test.zip)

And the result with the marnav library "VERSION 0.11.0" :
`!AIVDM,1,1,,A,15RTgt0PAs`lnwJKcjLph6f408CQ,0*52`

Thanks,
Ronan.

**Comment by mariokonrad** [comment]
Hello Ronan,

I checked version 0.11.0 (3eae9870f52d52f0f045708f924c5be6ddc70184).
Using your code (minus the ROS stuff), I get the following results:
```
lon= 123.395382  => !AIVDM,1,1,,A,15RTgt0PAs`lnwJKcjLph6f408CQ,0*52
lon=-123.395382  => !AIVDM,1,1,,A,15RTgt0PAso;90TKcjLph6f408CQ,0*04
```

Current HEAD (0c50454194ea7fb7acfc536efb26e2f0be1f6b1a) prints:
```
lon= 123.395382  => !AIVDM,1,1,,A,15RTgt0PAs`lnwJKcjLph6g208CQ,0*55
lon=-123.395382  => !AIVDM,1,1,,A,15RTgt0PAso;90TKcjLph6g208CQ,0*03
```
The difference is caused by a bug fix regarding the `timestamp` in `ais::message_01`, see bd9d2521b1f409924ce8e2462b0547b7996a4e88.

Both versions show the correct positive and negative longitudes when testing with http://ais.tbsalling.dk/, https://rl.se/aivdm and https://www.aggsoft.com/ais-decoder.htm

I cannot reproduce the `0` you get in longitude.

**Comment by rdouguet** [comment]
Hello Mario,
,
I re-build the version 0.11.0 on my computer and I obtain the same result than you. The latitude and longitude, positive and negative, are correct.

The next week, I will check on my embedded board (Jetson AGX Xavier) where is my problem.... Maybe I did an error as I integrated this library on ROS package. In any case the problem does not come from the library.

Thanks for your help.
Ronan

**Comment by mariokonrad** [comment]
May I ask which compiler you are using and what the target architecture is? Presumably ARM, but there are differences (32/64bit, with/without floating point unit, etc.)

**Comment by rdouguet** [comment]
Hello Mario,

Indeed, the error is related to the architecture that I use, I finally found it :)

The error comes from the different behaviors for casting negative float to unsigned int between Intel and ARM architecture.
I read this here : https://embeddeduse.com/2013/08/25/casting-a-negative-float-to-an-unsigned-int/

One solution to fix the problem is to cast two times the value (first to signed int and then to unsigned int).
For me, the error was into **deg_to** function. Maybe there are other negative casts in this library. 
I used "gcc 7.5.0" compiler.

```
/// Converts angles in degrees to I4 values, used in AIS messages.
///
/// This conversion function is suitable for both, latitudes and longitudes.
///
/// @param[in] value The angle to convert, may be positive or negative.
/// @param[in] bits Number of bits of information in the AIS message.
/// @param[in] scale Angle scaling.
/// @return The converted angle to be used in AIS messages.
static uint32_t deg_to(double value, std::size_t bits, angle_scale scale)
{
	assert(bits > 0);
	assert(bits < 33);

	uint32_t mask = std::numeric_limits<uint32_t>::max();
	mask <<= bits;

	return static_cast<uint32_t>(static_cast<int32_t>(floor((60.0 * scale_value(scale)) * value))) & ~mask;
}
```
Now all seems ok :) 

Thank for your help Mario. I don't know if you can commit this modification in your code ?

Ronan.

**Comment by mariokonrad** [comment]
Hi Ronan,

thanks for the investigation! My use cases for the library were `x86_64` only so far.
I'll add ARM and aarch64 builds and unit test execution and include your finding.

Mario

**Comment by mariokonrad** [comment]
Apparently there is no more discussion in quite some time. I consider it solved.
