### ISSUE TITLE
Build failure with GCC 12 on ARM64

### ISSUE THREAD

**Issue by nohal** [mariokonrad/marnav#52]
I have switched my CI builds to the current marnav codebase and it reveals a build failure specific to GCC12 on ARM64: https://app.circleci.com/pipelines/github/nohal/nsk_pi/13/workflows/89dce313-bcb0-4363-93ee-fae1205148e2/jobs/150?invite=true#step-102-4362

**Comment by mariokonrad** [comment]
Interesting find. It seems this error does not trigger for GCC-10 (see cmake presets) and GCC-11, but only for GCC-12 on ARM64 with optimization -O3 but not with -O2. For comparison:

- ARM64 / gcc-12.2.0 / O2: https://godbolt.org/z/3YPsz7MbT : compiles
- ARM64 / gcc-12.2.0 / O3: https://godbolt.org/z/bz6jx3PrP : fails

GCC-trunk shows the problem as well. I could not reproduce the issue with GCC (any version) for x86_64 targets.

**Comment by mariokonrad** [comment]
c4ae1473d72ed151aa7c224dda7b7a44c1217e7a circumvents the issue for now. In the future when I remove older compilers stuff from `<charconv>` or `<format>` can be used.

Thanks for reporting the issue!

**Comment by nohal** [comment]
Thanks!
