### ISSUE TITLE
Problem with fmt version

### ISSUE THREAD

**Issue by filochard** [mariokonrad/marnav#56]
Hello
I'm packaging some marine programs for a Linux distribution (OpenCPN and its plugins)
For this we use our system libraries
I intended to package opencpn-nsk-plugin which uses marnav... as a BuildRequire
So I need to build and package marnav
And then problems appear : 
- if I build and package marnav as it is in your source, I get conflict since our fmt version is different from yours
- if I try to build marnav upon a more recent fmt version it's not possible since two required headers don't exist anymore in recent fmt version : no more posix.h nor locale.h in fmt include (they still exist in your extern/fmt/include/fmt folder) (version6)

Would it be not to much difficult for you to use a more recent version of fmt ? for compatibility with recent linux distributions

Thanks for this
Philippe (filochard)

**Comment by mariokonrad** [comment]
Hi Philippe,

For a quick fix on your side, you could build the library without tools (e.g. `nmeatool`). The library itself does not have any dependencies other than std library. For your case you could omit building tools and tests for now.
The corresponding CMake options:
- `ENABLE_TESTS`
- `ENABLE_TOOLS`

Set both to `FALSE` and you're there.

Updating fmt is not a big deal. However, the plan has been to upgrade to C++20 and remove old compilers that do not support the `<format>` header.

**Comment by filochard** [comment]
Hi
Thanks for your reply
I will omit to build tools
(but I don't know yet if they are needed or not by the Opencpn-plugin I want to  build, I will try after this)

**Comment by nohal** [comment]
no, the tools are not needed

**Comment by filochard** [comment]
Hi Mario
Hi Pavel

Thanks to both of you
I finally could package without the TOOL option (no more conflict with other fmt library from the distribution)
and I could package Pavel's opencpn-nsk-plugin which requires marnav to be built but fortunately doesn't need the marnav tools

Best Regards
