### ISSUE TITLE
NEW MOB Sentence..

### ISSUE THREAD

**Issue by TR-Martin** [mariokonrad/marnav#6]
You're probably aware but I just wanted to make sure,  I didn't see it in the source code:
NMEA has added a new sentence to the 4.10 spec for Man overboard.
$--MOB, blah, blah,blah,,,,,,0*2F<CR><LF> 

I know the whole legality of 'Reverse Engineering' a proprietary spec is tight rope to walk, derivative work, <insert more legalese here>,  but the technical bulletin  I found from NMEA on the Man overboard sentence specifically states it's a public document if you want to research it. 
"I specifically did not put a link to the document here to maintain your legal cleanliness"
It's easy enough to find... 

Hope this helps, I only bring it up for completeness...

Cheers,
TR. Martin

**Comment by mariokonrad** [comment]
Thanks for the hint. I'm always looking for information that I can use legally.

Before I do research, do you know in what legal context this "public document" resides? A document can be public but under a license that specifically allows or forbids stuff. Specifically, is it derivative work to implement stuff that is described in this "public document"?

**Comment by TR-Martin** [comment]
Well the "Technical Bulletin" itself is pretty terse. there's an introduction (below):

> An amendment is a technical specification that is publically available and applies to the current version as specified.  
> The content of the amendment will be incorporated into the next released version of the NMEA 0183 standard.
> This document contains the final approved NMEA 0183 Man Overboard Notification (MOB) sentence. This sentence was completed with assistance from the USCG, Inmarsat, NMEA, IEC, and additional maritime industry partners.  

After the introduction the technical information begins and that's about it (it's a 2 page word document). The NMEA website (where this document originates from) has some copyright babble in the terms & conditions, but is silent about derived work or licensing. 

It looks like public information, but then I'm not a lawyer, just programmer with a boat. 

Hope that helps
TR. Martin

**Comment by mariokonrad** [comment]
Thanks.

> I'm not a lawyer, just programmer with a boat.

(Un)fortunately, me too.
