### ISSUE TITLE
64 bit mmsi

### ISSUE THREAD

**Issue by abdolahsa** [mariokonrad/marnav#9]
hello and thanks for your neat works.
you've supposed that mmsi is 32 bit but there are 64 bit mmsi also.
I've tried to correct it, in utils::mmsi you've declared a type with name value_type, I changed it to u_int64 but in ais message classes (message_1,2,...) you've defined bitset<..., u_int32> mmsi, so conversion is cumbersome.

**Comment by mariokonrad** [comment]
I do not know what you mean by "64 bit mmsi".

MMSI has 9 decimal digits (see [wikipedia](https://en.wikipedia.org/wiki/Maritime_Mobile_Service_Identity), or [here](https://www.navcen.uscg.gov/index.php?pageName=mtMmsi) as well).

In AIS messages (see [here](http://catb.org/gpsd/AIVDM.html)), MMSIs are transmitted in 30 bits.

Would you please elaborate and provide sources why a 64 bit unsinged inteteger would be necessary.

**Comment by abdolahsa** [comment]
Indeed I work with AIS message and 30 bits can be wrapped in long long type.

**Comment by abdolahsa** [comment]
thanks, I misunderstand somethings. I've received bad data and I thought that it must be 64 bit. excuse me.

**Comment by mariokonrad** [comment]
No problem.
